### ISSUE TITLE
Where can I contribute to the code?

### ISSUE THREAD

**Issue by H2CO3** [ferzkopp/SDL_gfx#1]
Hi,

I've searched here, on SourceForge and your site, but in none of the repos could I find an official way to submit a patch to SDL2_gfx. I've implemented a few basic gradient drawing primitives, and I think it might be useful to add them to the graphics primitives library. Where should I start if I'd like to contribute?

Thanks, Árpád

**Comment by ferzkopp** [comment]
Hi Árpád,

you can send me a patch against the HEAD on sourceforge - 
https://sourceforge.net/p/sdl2gfx/code/HEAD/tree/) and I'll review and 
integrate it.

Cheers,
Andreas

**Comment by H2CO3** [comment]
Hi Andreas,

Thanks for you prompt reply. I'll do so.

Regards, Árpád

**Comment by H2CO3** [comment]
Hi,

I've looked for the opportunity of adding patches on SourceForge, but opening tickets is not possible, and there's neither a `/patches` or a `/bugs` subpage for the project (I've seen other projects use these pages for submitting patches).

I can't `svn commit` either because I only have read-only access, obviously.

So I'm sorry but I don't really know how I am supposed to submit my patch request through SourceForge. Hence, I'm attaching my patch hereby: https://gist.github.com/H2CO3/b2284aa2f03c8ec9f4ad

Thanks for your kind understanding.

**Comment by ferzkopp** [comment]
Thanks - this will work, not sure what they did to SF, as they used to have a working ticketing and bug reporting system with the ability to attache patches. I had a quick look at your code and the functionality makes sense. I won't put it in SDL2_gfxPrimitives.c since it is not a primitive operating on a renderer, but really a texture helper warranting a new SDL2_texture.c file and .h namespace. There are also various opportunities to optimize a bit. It may take a weekend or two for me to integrate your changes. --Andreas

**Comment by H2CO3** [comment]
Awesome, thanks!
